"""
I Ching hexagram lookup table — all 64 hexagrams (King Wen sequence).

Each record contains:
  number           — 1–64 (King Wen order)
  name_chinese     — Traditional Chinese name
  name_english     — Standard Wilhelm/Baynes English name
  image            — One sentence describing the hexagram image
  judgment         — One sentence core judgment from the text
  core_theme       — 2–3 word theme
  polarity         — "yang" (≥4 yang lines), "yin" (≤2 yang lines),
                     or "balanced" (exactly 3 yang lines)
  domain_affinities — Domains this hexagram speaks most directly to
  tendency_direction — "forward" | "pause" | "retreat" | "transform"

Polarity is derived from line counts (yang = solid line):
  yang  : 4, 5, or 6 yang lines
  yin   : 0, 1, or 2 yang lines
  balanced: 3 yang lines
"""

from __future__ import annotations

HEXAGRAMS: list[dict] = [
    {
        "number": 1,
        "name_chinese": "乾",
        "name_english": "The Creative",
        "image": "Heaven over heaven: the creative force redoubles itself, signifying pure initiating power.",
        "judgment": "The Creative brings supreme success through strength and unwavering perseverance.",
        "core_theme": "Pure initiation",
        "polarity": "yang",
        "domain_affinities": ["career", "direction", "finances"],
        "tendency_direction": "forward",
    },
    {
        "number": 2,
        "name_chinese": "坤",
        "name_english": "The Receptive",
        "image": "Earth over earth: the receptive ground yields in all directions without resistance.",
        "judgment": "The Receptive brings supreme success through the mare's perseverance — leading astray, following leads to good fortune.",
        "core_theme": "Yielding receptivity",
        "polarity": "yin",
        "domain_affinities": ["relationships", "health", "general"],
        "tendency_direction": "pause",
    },
    {
        "number": 3,
        "name_chinese": "屯",
        "name_english": "Difficulty at the Beginning",
        "image": "Water over thunder: new growth struggles upward through the resistance of initial formation.",
        "judgment": "Difficulty at the beginning brings supreme good fortune if perseverance is maintained without forcing premature advance.",
        "core_theme": "Difficult beginnings",
        "polarity": "yin",
        "domain_affinities": ["career", "direction", "general"],
        "tendency_direction": "transform",
    },
    {
        "number": 4,
        "name_chinese": "蒙",
        "name_english": "Youthful Folly",
        "image": "Mountain over water: the spring at the foot of the mountain seeks its teacher before flowing.",
        "judgment": "Youthful folly brings success when the inexperienced student seeks the teacher, not the reverse.",
        "core_theme": "Seeking instruction",
        "polarity": "yin",
        "domain_affinities": ["direction", "career", "general"],
        "tendency_direction": "pause",
    },
    {
        "number": 5,
        "name_chinese": "需",
        "name_english": "Waiting",
        "image": "Water over heaven: clouds gather above heaven, withholding rain until the moment is right.",
        "judgment": "Waiting with sincere confidence brings good fortune; crossing the great water succeeds when the time has come.",
        "core_theme": "Trusting the wait",
        "polarity": "yang",
        "domain_affinities": ["career", "relationships", "direction"],
        "tendency_direction": "pause",
    },
    {
        "number": 6,
        "name_chinese": "訟",
        "name_english": "Conflict",
        "image": "Heaven over water: heaven and water move in opposing directions, generating unavoidable tension.",
        "judgment": "Conflict — sincerity meets obstruction; cautious retreat to the midpoint brings good fortune, pressing through to the end brings misfortune.",
        "core_theme": "Resolving conflict",
        "polarity": "yang",
        "domain_affinities": ["relationships", "career", "direction"],
        "tendency_direction": "pause",
    },
    {
        "number": 7,
        "name_chinese": "師",
        "name_english": "The Army",
        "image": "Earth over water: water hidden within the earth, marshalled and moving in disciplined order.",
        "judgment": "The army succeeds through discipline and a capable commander; the elder receives reward.",
        "core_theme": "Disciplined force",
        "polarity": "yin",
        "domain_affinities": ["career", "direction", "general"],
        "tendency_direction": "forward",
    },
    {
        "number": 8,
        "name_chinese": "比",
        "name_english": "Holding Together",
        "image": "Water over earth: water rests upon the earth, naturally uniting with all it touches.",
        "judgment": "Holding together brings good fortune; examine yourself and join before the one who hesitates misses the joining.",
        "core_theme": "Forming alliance",
        "polarity": "yin",
        "domain_affinities": ["relationships", "career", "general"],
        "tendency_direction": "forward",
    },
    {
        "number": 9,
        "name_chinese": "小畜",
        "name_english": "Small Taming",
        "image": "Wind over heaven: wind drives across heaven, gathering clouds that withhold their rain.",
        "judgment": "The taming power of the small brings success; dense clouds but no rain from the western region.",
        "core_theme": "Small restraint",
        "polarity": "yang",
        "domain_affinities": ["career", "finances", "direction"],
        "tendency_direction": "pause",
    },
    {
        "number": 10,
        "name_chinese": "履",
        "name_english": "Treading",
        "image": "Heaven over lake: the lake below heaven, the place where proper conduct is required above all.",
        "judgment": "Treading upon the tiger's tail — if it does not bite, supreme success follows right conduct.",
        "core_theme": "Careful conduct",
        "polarity": "yang",
        "domain_affinities": ["career", "direction", "relationships"],
        "tendency_direction": "forward",
    },
    {
        "number": 11,
        "name_chinese": "泰",
        "name_english": "Peace",
        "image": "Earth over heaven: heaven and earth in intimate communion, their energies exchanging freely.",
        "judgment": "Peace — the small departs, the great approaches; good fortune through the harmonious union of opposites.",
        "core_theme": "Harmonious flow",
        "polarity": "balanced",
        "domain_affinities": ["career", "relationships", "finances"],
        "tendency_direction": "forward",
    },
    {
        "number": 12,
        "name_chinese": "否",
        "name_english": "Standstill",
        "image": "Heaven over earth: heaven and earth separated, their energies pulling away from each other.",
        "judgment": "Standstill — the great departs and the small approaches; stagnation does not favour the perseverance of the superior person.",
        "core_theme": "Blocked stagnation",
        "polarity": "balanced",
        "domain_affinities": ["career", "finances", "relationships"],
        "tendency_direction": "retreat",
    },
    {
        "number": 13,
        "name_chinese": "同人",
        "name_english": "Fellowship",
        "image": "Heaven over fire: fire rises toward heaven, bringing people of like mind together in the open.",
        "judgment": "Fellowship in the open — success through clarity of purpose and crossing the great water together.",
        "core_theme": "Open fellowship",
        "polarity": "yang",
        "domain_affinities": ["career", "relationships", "direction"],
        "tendency_direction": "forward",
    },
    {
        "number": 14,
        "name_chinese": "大有",
        "name_english": "Great Possession",
        "image": "Fire over heaven: the sun at the zenith illuminates all that lies beneath heaven.",
        "judgment": "Great possession — supreme success through inner clarity united with outward strength.",
        "core_theme": "Radiant abundance",
        "polarity": "yang",
        "domain_affinities": ["career", "finances", "direction"],
        "tendency_direction": "forward",
    },
    {
        "number": 15,
        "name_chinese": "謙",
        "name_english": "Modesty",
        "image": "Earth over mountain: the mountain concealed beneath the earth, its heights hidden by humility.",
        "judgment": "Modesty — success; the superior person carries things through to completion.",
        "core_theme": "Humble restraint",
        "polarity": "yin",
        "domain_affinities": ["relationships", "career", "direction"],
        "tendency_direction": "pause",
    },
    {
        "number": 16,
        "name_chinese": "豫",
        "name_english": "Enthusiasm",
        "image": "Thunder over earth: thunder bursts from the earth, awakening dormant energy into joyful movement.",
        "judgment": "Enthusiasm is propitious for installing helpers and setting armies in motion.",
        "core_theme": "Joyful movement",
        "polarity": "yin",
        "domain_affinities": ["career", "direction", "general"],
        "tendency_direction": "forward",
    },
    {
        "number": 17,
        "name_chinese": "隨",
        "name_english": "Following",
        "image": "Lake over thunder: thunder rests within the lake, moving with the season's natural rhythm.",
        "judgment": "Following brings supreme success — no blame comes from perseverance in what is right.",
        "core_theme": "Natural following",
        "polarity": "balanced",
        "domain_affinities": ["direction", "relationships", "general"],
        "tendency_direction": "forward",
    },
    {
        "number": 18,
        "name_chinese": "蠱",
        "name_english": "Work on the Decayed",
        "image": "Mountain over wind: the wind blows beneath the mountain where neglect has allowed decay.",
        "judgment": "Work on what has been spoiled brings supreme success; it furthers to cross the great water.",
        "core_theme": "Correcting decay",
        "polarity": "balanced",
        "domain_affinities": ["career", "direction", "general"],
        "tendency_direction": "transform",
    },
    {
        "number": 19,
        "name_chinese": "臨",
        "name_english": "Approach",
        "image": "Earth over lake: the earth looks down upon the lake, bringing the authority of approach.",
        "judgment": "Approach — supreme success through perseverance; when the eighth month comes, misfortune.",
        "core_theme": "Drawing near",
        "polarity": "yin",
        "domain_affinities": ["career", "relationships", "direction"],
        "tendency_direction": "forward",
    },
    {
        "number": 20,
        "name_chinese": "觀",
        "name_english": "Contemplation",
        "image": "Wind over earth: the wind moves across the earth, the watchtower commands a view of all below.",
        "judgment": "Contemplation — the sacred washing has been performed; sincerity raises the offering in truth.",
        "core_theme": "Witnessing clearly",
        "polarity": "yin",
        "domain_affinities": ["direction", "general", "relationships"],
        "tendency_direction": "pause",
    },
    {
        "number": 21,
        "name_chinese": "噬嗑",
        "name_english": "Biting Through",
        "image": "Fire over thunder: lightning strikes through the obstacle, biting through with decisive force.",
        "judgment": "Biting through — success; it is favourable to let justice be administered.",
        "core_theme": "Breaking through",
        "polarity": "balanced",
        "domain_affinities": ["career", "direction", "finances"],
        "tendency_direction": "forward",
    },
    {
        "number": 22,
        "name_chinese": "賁",
        "name_english": "Grace",
        "image": "Mountain over fire: fire illuminates the mountain's base, adorning it with graceful light.",
        "judgment": "Grace — success in small matters; it is not favourable to attempt great undertakings.",
        "core_theme": "Graceful adornment",
        "polarity": "balanced",
        "domain_affinities": ["relationships", "direction", "general"],
        "tendency_direction": "pause",
    },
    {
        "number": 23,
        "name_chinese": "剝",
        "name_english": "Splitting Apart",
        "image": "Mountain over earth: the mountain erodes down to the earth, five yin lines stripping the last yang.",
        "judgment": "Splitting apart — it does not further to go anywhere; endure in stillness.",
        "core_theme": "Gradual erosion",
        "polarity": "yin",
        "domain_affinities": ["direction", "health", "general"],
        "tendency_direction": "retreat",
    },
    {
        "number": 24,
        "name_chinese": "復",
        "name_english": "Return",
        "image": "Earth over thunder: thunder stirs beneath the earth at the winter solstice, the turning point arrives.",
        "judgment": "Return brings good fortune; the one yang line returns; going out and coming in without error.",
        "core_theme": "Natural return",
        "polarity": "yin",
        "domain_affinities": ["direction", "health", "career"],
        "tendency_direction": "forward",
    },
    {
        "number": 25,
        "name_chinese": "無妄",
        "name_english": "Innocence",
        "image": "Heaven over thunder: under heaven, thunder moves — all things follow their natural uncorrupted course.",
        "judgment": "Innocence — supreme success through perseverance; those who are not in harmony with what is natural invite misfortune.",
        "core_theme": "Unspoiled nature",
        "polarity": "yang",
        "domain_affinities": ["direction", "career", "general"],
        "tendency_direction": "forward",
    },
    {
        "number": 26,
        "name_chinese": "大畜",
        "name_english": "Great Taming",
        "image": "Mountain over heaven: the immensity of heaven is held within the mountain, power in reserve.",
        "judgment": "The taming power of the great — perseverance brings good fortune; not eating at home brings good fortune.",
        "core_theme": "Holding power",
        "polarity": "yang",
        "domain_affinities": ["career", "finances", "direction"],
        "tendency_direction": "pause",
    },
    {
        "number": 27,
        "name_chinese": "頤",
        "name_english": "Nourishment",
        "image": "Mountain over thunder: thunder at the foot of the mountain — the image of the corners of the mouth.",
        "judgment": "Nourishment — perseverance brings good fortune; contemplate what you nourish and how.",
        "core_theme": "Conscious nourishment",
        "polarity": "yin",
        "domain_affinities": ["health", "direction", "relationships"],
        "tendency_direction": "pause",
    },
    {
        "number": 28,
        "name_chinese": "大過",
        "name_english": "Great Excess",
        "image": "Lake over wind: the lake rises above the treetops, the ridgepole sags under critical weight.",
        "judgment": "The ridgepole sags — it furthers to go somewhere; success.",
        "core_theme": "Critical overload",
        "polarity": "yang",
        "domain_affinities": ["career", "direction", "health"],
        "tendency_direction": "transform",
    },
    {
        "number": 29,
        "name_chinese": "坎",
        "name_english": "The Abysmal",
        "image": "Water over water: danger upon danger, the abyss repeated without respite.",
        "judgment": "The abysmal — if you are sincere, the heart grows confident and success is achieved through the danger.",
        "core_theme": "Abiding through danger",
        "polarity": "yin",
        "domain_affinities": ["direction", "health", "career"],
        "tendency_direction": "transform",
    },
    {
        "number": 30,
        "name_chinese": "離",
        "name_english": "The Clinging",
        "image": "Fire over fire: brightness doubled upon brightness, clinging together for illumination.",
        "judgment": "The clinging — perseverance brings success; caring for the cow brings good fortune.",
        "core_theme": "Mutual illumination",
        "polarity": "yang",
        "domain_affinities": ["career", "direction", "relationships"],
        "tendency_direction": "forward",
    },
    {
        "number": 31,
        "name_chinese": "咸",
        "name_english": "Influence",
        "image": "Lake over mountain: the lake rests upon the mountain, attracting and being attracted.",
        "judgment": "Influence — success; perseverance is favourable; taking a maiden to wife brings good fortune.",
        "core_theme": "Spontaneous attraction",
        "polarity": "balanced",
        "domain_affinities": ["relationships", "direction", "general"],
        "tendency_direction": "forward",
    },
    {
        "number": 32,
        "name_chinese": "恆",
        "name_english": "Duration",
        "image": "Thunder over wind: thunder and wind reinforce each other in enduring and self-renewing action.",
        "judgment": "Duration — success without blame; it furthers to have somewhere to go; perseverance brings good fortune.",
        "core_theme": "Enduring continuity",
        "polarity": "balanced",
        "domain_affinities": ["career", "relationships", "direction"],
        "tendency_direction": "pause",
    },
    {
        "number": 33,
        "name_chinese": "遯",
        "name_english": "Retreat",
        "image": "Heaven over mountain: the mountain rises but heaven withdraws above it in strategic distance.",
        "judgment": "Retreat — success; in small matters, the perseverance of timely withdrawal brings good fortune.",
        "core_theme": "Strategic withdrawal",
        "polarity": "yang",
        "domain_affinities": ["career", "direction", "general"],
        "tendency_direction": "retreat",
    },
    {
        "number": 34,
        "name_chinese": "大壯",
        "name_english": "Great Power",
        "image": "Thunder over heaven: great thunder stirs above heaven, four strong yang lines advance.",
        "judgment": "Great power — perseverance furthers.",
        "core_theme": "Advancing power",
        "polarity": "yang",
        "domain_affinities": ["career", "direction", "finances"],
        "tendency_direction": "forward",
    },
    {
        "number": 35,
        "name_chinese": "晉",
        "name_english": "Progress",
        "image": "Fire over earth: the sun rises over the earth, illuminating progress with clarity from above.",
        "judgment": "Progress — the powerful prince is presented with horses in great numbers; in a single day he is thrice granted audience.",
        "core_theme": "Clear progress",
        "polarity": "yin",
        "domain_affinities": ["career", "direction", "finances"],
        "tendency_direction": "forward",
    },
    {
        "number": 36,
        "name_chinese": "明夷",
        "name_english": "Darkening of the Light",
        "image": "Earth over fire: the sun sinks beneath the earth, the light deliberately concealed for protection.",
        "judgment": "Darkening of the light — perseverance through adversity.",
        "core_theme": "Protecting light",
        "polarity": "yin",
        "domain_affinities": ["career", "direction", "general"],
        "tendency_direction": "retreat",
    },
    {
        "number": 37,
        "name_chinese": "家人",
        "name_english": "The Family",
        "image": "Wind over fire: wind rises from fire, the family maintained through inner warmth and proper order.",
        "judgment": "The family — perseverance of the woman brings good fortune.",
        "core_theme": "Family order",
        "polarity": "yang",
        "domain_affinities": ["relationships", "career", "general"],
        "tendency_direction": "pause",
    },
    {
        "number": 38,
        "name_chinese": "睽",
        "name_english": "Opposition",
        "image": "Fire over lake: fire moves upward and lake moves downward, their natures opposed.",
        "judgment": "Opposition — in small matters, good fortune; the separate must find the common ground.",
        "core_theme": "Creative opposition",
        "polarity": "yang",
        "domain_affinities": ["relationships", "direction", "career"],
        "tendency_direction": "transform",
    },
    {
        "number": 39,
        "name_chinese": "蹇",
        "name_english": "Obstruction",
        "image": "Water over mountain: water on the mountain — the abyss lies ahead, the steep behind.",
        "judgment": "Obstruction — the southwest furthers; see the great person; perseverance brings good fortune.",
        "core_theme": "Patient preparation",
        "polarity": "yin",
        "domain_affinities": ["direction", "career", "travel"],
        "tendency_direction": "pause",
    },
    {
        "number": 40,
        "name_chinese": "解",
        "name_english": "Deliverance",
        "image": "Thunder over water: thunder and rain release the pent tension, the knot loosens.",
        "judgment": "Deliverance — the southwest brings good fortune; going and coming back without delay brings good fortune.",
        "core_theme": "Welcome release",
        "polarity": "yin",
        "domain_affinities": ["direction", "career", "relationships"],
        "tendency_direction": "forward",
    },
    {
        "number": 41,
        "name_chinese": "損",
        "name_english": "Decrease",
        "image": "Mountain over lake: the lake at the base of the mountain diminishes below to increase above.",
        "judgment": "Decrease — sincerity in decrease brings supreme good fortune without blame.",
        "core_theme": "Willing decrease",
        "polarity": "balanced",
        "domain_affinities": ["finances", "career", "direction"],
        "tendency_direction": "transform",
    },
    {
        "number": 42,
        "name_chinese": "益",
        "name_english": "Increase",
        "image": "Wind over thunder: wind and thunder amplify each other, decrease above brings increase below.",
        "judgment": "Increase — it furthers to undertake something; it furthers to cross the great water.",
        "core_theme": "Generous increase",
        "polarity": "balanced",
        "domain_affinities": ["career", "finances", "relationships"],
        "tendency_direction": "forward",
    },
    {
        "number": 43,
        "name_chinese": "夬",
        "name_english": "Breakthrough",
        "image": "Lake over heaven: the lake rises above heaven, a single yin line yields to five yang in breakthrough.",
        "judgment": "Breakthrough — the matter must be announced at the royal court; truth must be spoken even at personal risk.",
        "core_theme": "Decisive breakthrough",
        "polarity": "yang",
        "domain_affinities": ["career", "direction", "finances"],
        "tendency_direction": "forward",
    },
    {
        "number": 44,
        "name_chinese": "姤",
        "name_english": "Coming to Meet",
        "image": "Heaven over wind: wind moves beneath heaven, the unexpected encounter arrives unbidden.",
        "judgment": "Coming to meet — the maiden is powerful; do not marry such a woman; be watchful.",
        "core_theme": "Unexpected encounter",
        "polarity": "yang",
        "domain_affinities": ["relationships", "career", "general"],
        "tendency_direction": "pause",
    },
    {
        "number": 45,
        "name_chinese": "萃",
        "name_english": "Gathering Together",
        "image": "Lake over earth: the lake gathers all waters of the earth, the great assembly convenes.",
        "judgment": "Gathering together — the king approaches his temple; seeing the great person brings good fortune.",
        "core_theme": "Collective gathering",
        "polarity": "yin",
        "domain_affinities": ["career", "relationships", "direction"],
        "tendency_direction": "forward",
    },
    {
        "number": 46,
        "name_chinese": "升",
        "name_english": "Pushing Upward",
        "image": "Earth over wind: wind moves through the earth pushing upward, growth advances from within.",
        "judgment": "Pushing upward — supreme success; it furthers to see the great person; do not be apprehensive.",
        "core_theme": "Steady ascent",
        "polarity": "yin",
        "domain_affinities": ["career", "direction", "finances"],
        "tendency_direction": "forward",
    },
    {
        "number": 47,
        "name_chinese": "困",
        "name_english": "Oppression",
        "image": "Lake over water: the water has drained from the lake, the exhausted vessel stands depleted.",
        "judgment": "Oppression — success through perseverance; the great person brings good fortune through trust in adversity.",
        "core_theme": "Enduring adversity",
        "polarity": "balanced",
        "domain_affinities": ["direction", "career", "health"],
        "tendency_direction": "retreat",
    },
    {
        "number": 48,
        "name_chinese": "井",
        "name_english": "The Well",
        "image": "Water over wind: wind moves beneath the water, the well nourishes from an inexhaustible source.",
        "judgment": "The well — no loss, no gain; the town may change but the well does not change.",
        "core_theme": "Inexhaustible source",
        "polarity": "balanced",
        "domain_affinities": ["direction", "health", "relationships"],
        "tendency_direction": "pause",
    },
    {
        "number": 49,
        "name_chinese": "革",
        "name_english": "Revolution",
        "image": "Lake over fire: fire and lake oppose each other, the old order burns away in transformation.",
        "judgment": "Revolution — on your own day, supreme success through perseverance; remorse vanishes.",
        "core_theme": "Necessary revolution",
        "polarity": "yang",
        "domain_affinities": ["career", "direction", "general"],
        "tendency_direction": "transform",
    },
    {
        "number": 50,
        "name_chinese": "鼎",
        "name_english": "The Cauldron",
        "image": "Fire over wind: wind feeds the fire beneath the cauldron that transforms raw into nourishment.",
        "judgment": "The cauldron — supreme good fortune and success.",
        "core_theme": "Sacred nourishment",
        "polarity": "yang",
        "domain_affinities": ["career", "direction", "health"],
        "tendency_direction": "forward",
    },
    {
        "number": 51,
        "name_chinese": "震",
        "name_english": "The Arousing",
        "image": "Thunder over thunder: doubled shock, the thunder that awakens and sets everything in motion.",
        "judgment": "The arousing — shock brings success; the thunderclap frightens, but laughter follows.",
        "core_theme": "Awakening shock",
        "polarity": "yin",
        "domain_affinities": ["direction", "career", "general"],
        "tendency_direction": "transform",
    },
    {
        "number": 52,
        "name_chinese": "艮",
        "name_english": "Keeping Still",
        "image": "Mountain over mountain: doubled stillness, the mountain at perfect rest in its own nature.",
        "judgment": "Keeping still — keeping the back still so that the ego is no longer felt; no error.",
        "core_theme": "Complete stillness",
        "polarity": "yin",
        "domain_affinities": ["health", "direction", "general"],
        "tendency_direction": "pause",
    },
    {
        "number": 53,
        "name_chinese": "漸",
        "name_english": "Gradual Progress",
        "image": "Wind over mountain: the tree grows slowly on the mountain, rooted and gradual in its advance.",
        "judgment": "Gradual progress — the maiden is given in marriage; good fortune through perseverance.",
        "core_theme": "Steady progress",
        "polarity": "balanced",
        "domain_affinities": ["career", "relationships", "direction"],
        "tendency_direction": "forward",
    },
    {
        "number": 54,
        "name_chinese": "歸妹",
        "name_english": "The Marrying Maiden",
        "image": "Thunder over lake: thunder above the lake, the undertaking carries its own complications.",
        "judgment": "The marrying maiden — undertakings bring misfortune; nothing that would further.",
        "core_theme": "Complicated undertaking",
        "polarity": "balanced",
        "domain_affinities": ["relationships", "direction", "general"],
        "tendency_direction": "transform",
    },
    {
        "number": 55,
        "name_chinese": "豐",
        "name_english": "Abundance",
        "image": "Thunder over fire: thunder and lightning combine in the moment of peak fullness.",
        "judgment": "Abundance — the king attains fullness; do not be sad; be like the sun at midday.",
        "core_theme": "Peak fullness",
        "polarity": "balanced",
        "domain_affinities": ["career", "finances", "direction"],
        "tendency_direction": "forward",
    },
    {
        "number": 56,
        "name_chinese": "旅",
        "name_english": "The Wanderer",
        "image": "Fire over mountain: the wandering fire moves across the mountain without attachment to place.",
        "judgment": "The wanderer — success through what is small; perseverance of the wanderer brings good fortune.",
        "core_theme": "Detached movement",
        "polarity": "balanced",
        "domain_affinities": ["travel", "direction", "career"],
        "tendency_direction": "forward",
    },
    {
        "number": 57,
        "name_chinese": "巽",
        "name_english": "The Gentle",
        "image": "Wind over wind: wind following wind, gentle persistence penetrating where force cannot.",
        "judgment": "The gentle — success through small perseverance; it furthers to have somewhere to go.",
        "core_theme": "Gentle penetration",
        "polarity": "yang",
        "domain_affinities": ["career", "direction", "relationships"],
        "tendency_direction": "pause",
    },
    {
        "number": 58,
        "name_chinese": "兌",
        "name_english": "The Joyous",
        "image": "Lake over lake: doubled joy — the lake refreshes itself in the open expression of gladness.",
        "judgment": "The joyous — success; perseverance is favourable.",
        "core_theme": "Genuine joy",
        "polarity": "yang",
        "domain_affinities": ["relationships", "career", "general"],
        "tendency_direction": "forward",
    },
    {
        "number": 59,
        "name_chinese": "渙",
        "name_english": "Dispersion",
        "image": "Wind over water: wind moves over water dispersing rigid forms, barriers dissolve.",
        "judgment": "Dispersion — the king approaches his temple; it furthers to cross the great water.",
        "core_theme": "Dissolving barriers",
        "polarity": "balanced",
        "domain_affinities": ["career", "relationships", "direction"],
        "tendency_direction": "forward",
    },
    {
        "number": 60,
        "name_chinese": "節",
        "name_english": "Limitation",
        "image": "Water over lake: water fills the lake to its brim, the limit defines the vessel's purpose.",
        "judgment": "Limitation — success; galling limitation must not be persevered in.",
        "core_theme": "Proper limits",
        "polarity": "balanced",
        "domain_affinities": ["career", "finances", "direction"],
        "tendency_direction": "pause",
    },
    {
        "number": 61,
        "name_chinese": "中孚",
        "name_english": "Inner Truth",
        "image": "Wind over lake: wind over the lake reaches the innermost depths — sincerity penetrates all.",
        "judgment": "Inner truth — pigs and fishes; good fortune; sincerity crosses the great water.",
        "core_theme": "Inner sincerity",
        "polarity": "yang",
        "domain_affinities": ["relationships", "direction", "career"],
        "tendency_direction": "forward",
    },
    {
        "number": 62,
        "name_chinese": "小過",
        "name_english": "Small Excess",
        "image": "Thunder over mountain: the small bird flies higher than it should — small steps, not grand ones.",
        "judgment": "Small excess — success through perseverance; small matters may be done, great matters not.",
        "core_theme": "Small steps",
        "polarity": "yin",
        "domain_affinities": ["direction", "career", "general"],
        "tendency_direction": "pause",
    },
    {
        "number": 63,
        "name_chinese": "既濟",
        "name_english": "After Completion",
        "image": "Water over fire: water above fire — completion, all six lines in their proper alternating places.",
        "judgment": "After completion — success in small matters; the beginning brings good fortune, the end sees disorder.",
        "core_theme": "Completion maintenance",
        "polarity": "balanced",
        "domain_affinities": ["career", "direction", "relationships"],
        "tendency_direction": "pause",
    },
    {
        "number": 64,
        "name_chinese": "未濟",
        "name_english": "Before Completion",
        "image": "Fire over water: fire above water — not yet complete, the young fox nearly crosses the ice.",
        "judgment": "Before completion — success; the young fox nearly crosses but gets its tail wet.",
        "core_theme": "Threshold crossing",
        "polarity": "balanced",
        "domain_affinities": ["direction", "career", "relationships"],
        "tendency_direction": "transform",
    },
]

# ── Lookup index ──────────────────────────────────────────────────────────────

HEXAGRAM_BY_NUMBER: dict[int, dict] = {h["number"]: h for h in HEXAGRAMS}
