# Generated by Django 6.0.3 on 2026-04-03 04:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SessionContext',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_start', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('data_pool', models.JSONField(default=dict)),
                ('birth_time_tier', models.JSONField(blank=True, null=True)),
                ('moon_resolution', models.JSONField(blank=True, null=True)),
                ('iching_opted_in', models.BooleanField(default=False)),
                ('active_heads', models.JSONField(default=list)),
                ('queries', models.JSONField(default=list)),
                ('session_status', models.CharField(choices=[('active', 'Active'), ('complete', 'Complete'), ('abandoned', 'Abandoned')], default='active', max_length=20)),
                ('user_identifier', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'ordering': ['-session_start'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('profile_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_identifier', models.CharField(max_length=255, unique=True)),
                ('saved_at', models.DateTimeField(auto_now=True)),
                ('dob', models.JSONField(blank=True, null=True)),
                ('birth_time', models.JSONField(blank=True, null=True)),
                ('birth_location', models.JSONField(blank=True, null=True)),
                ('full_birth_name', models.CharField(blank=True, default='', max_length=255)),
                ('current_name', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
